force-app/main/default/objects/Patient__c/fields/Patient_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Patient_FirstName__c</fullName>
    <label>Patient FirstName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cl_2610_SchedulableApex.cls
global class Cl_2610_SchedulableApex implements Schedulable {

    public void execute(SchedulableContext sc){
        //can do the batch
        List<Patient__c> pt = [select id,Name,Patient_FirstName__c from Patient__c];
         List<Patient__c> pat = new List<Patient__c>();
        for(Patient__c p:pt){
            p.Patient_FirstName__c = 'batch apex';
            pat.add(p);
        }
        if(!pat.isEmpty()){
            update pat;
        }
          
    }
}