force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Account_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Is_Visit__c.field-meta.xml
<CustomField>
    <fullName>Is_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OneVisitPerAccount.cls
public class OneVisitPerAccount {

    public static void oneVisitPerDay(List<Visit__c> triggerNew){
        Set<Id>parentIds = new Set<Id>();
        for(Visit__c vs : triggernew){
            if(vs.Account__c != Null){
                parentIds.add(vs.Account__c);
            }
        }
        Map<id,Visit__c>visitMap = New Map<Id,Visit__c>([select id,Name,Is_Visit__c,Account__c,CreatedDate from Visit__c where Account__c In:parentIds order By createdDate DESC Limit 1]);
        for(Visit__c newRec : triggernew)
        {
           for(Visit__c oldRec: visitMap.values())
           {
             if(newRec.CreatedDate != oldRec.CreatedDate)
             {
                newRec.addError('Cannot create New Vist because there\'s another one created on this date.'); 
             }
           }
        }
    }
}