force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Account_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Is_Visit__c.field-meta.xml
<CustomField>
    <fullName>Is_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountVisitHandler.cls
public class AccountVisitHandler {

        public static void recentRecordIsLatestSetToTrue(List<Visit__c>triggernew){
        List<Visit__c> visitList = new List<Visit__c>();
        Set<Id>parentIds = new Set<Id>();
        for(Visit__c vs : triggernew){
            if(vs.Account__c != Null){
                parentIds.add(vs.Account__c);
            }
        }
        Map<id,Visit__c>visitMap = New Map<Id,Visit__c>([select id,Name,Is_Visit__c,Account__c from Visit__c where Account__c In:parentIds AND Is_Visit__c = true AND id NOT in:triggernew]);
        for(Visit__c vv : visitMap.values()){
            vv.Is_Visit__c = false;
            visitList.add(vv);  
            vv.addError('You can insert only 1 Visit per Account per day');
        }
        update visitList;
        }
    
}