force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Account_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Is_Visit__c.field-meta.xml
<CustomField>
    <fullName>Is_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountVisitsTest.cls
@IsTest
public class AccountVisitsTest {
@IsTest
    public static void isLatestCheckboxTrue(){
        Account acc = new Account();
        acc.Name='Test One';
        insert acc;
       
        Visit__c vv = new Visit__c();
        vv.Name='Testnew';
        vv.Is_Visit__c=true;
        vv.Account__c = acc.Id;
        insert vv;
        
        Visit__c vv1 = new Visit__c();
        vv1.Name='Testnew1';
        vv1.Is_Visit__c=true;
        vv1.Account__c =acc.Id;
        insert vv1;
        
        
        
        Visit__c result = [select id,Is_Visit__c from Visit__c where Name ='Testnew'];
        system.assertEquals(false, result.Is_Visit__c);
        
        
    }
  
}