force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Account_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Is_Visit__c.field-meta.xml
<CustomField>
    <fullName>Is_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OneVisitPerAccountParent.cls
public class OneVisitPerAccountParent {

    public static void oneVisitPerdayPerParent(List<Visit__c> triggerNew){
       List<Visit__c> visitList = new List<Visit__c>();
        Set<Id>parentIds = new Set<Id>();
        for(Visit__c vs : triggernew){
            if(vs.Account__c != Null){
                parentIds.add(vs.Account__c);
            }
        }
        List<Visit__c>vList = New List<Visit__c>([select id,Name,Is_Visit__c,CreatedDate,CreatedById,Account__c from Visit__c where CreatedDate=TODAY AND Account__c In:parentIds]);
        for(Visit__c vsList:vList){
            system.debug('VsList:'+vsList);
            
            if(vList.size() > 0 ){
                trigger.new[0].addError('Cannot create New Vist because there is another one created on this date.');
                
            }
        }
    }
}