force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Students__c/Students__c.object-meta.xml
<CustomObject>
    <label>Students</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Students__c/fields/Average__c.field-meta.xml
<CustomField>
    <fullName>Average__c</fullName>
    <label>Average</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Fathers_Name__c.field-meta.xml
<CustomField>
    <fullName>Fathers_Name__c</fullName>
    <label>Fathers Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Hindi__c.field-meta.xml
<CustomField>
    <fullName>Hindi__c</fullName>
    <label>Hindi</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Maths</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Social__c.field-meta.xml
<CustomField>
    <fullName>Social__c</fullName>
    <label>Social</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Students__c/fields/Telugu__c.field-meta.xml
<CustomField>
    <fullName>Telugu__c</fullName>
    <label>Telugu</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentsOperations.cls
public with sharing class StudentsOperations {
    
     @AuraEnabled
    public static List<Students__c>  studentlist(String name, String fathersName,Decimal telugu,Decimal hindi,Decimal english,Decimal maths,Decimal science,Decimal social) {
        Students__c stud = new Students__c();
        List<Students__c> studList = new List<Students__c> ();
        
        stud.Name = name;
        stud.Fathers_Name__c = fathersName;
        stud.Telugu__c = telugu;
        stud.Hindi__c = hindi;
        stud.English__c = english;
        stud.Maths__c = maths;
        stud.Science__c = science;
        stud.Social__c = social;
        
        stud.Sum__c = stud.Telugu__c + stud.Hindi__c + stud.English__c  + stud.Maths__c + stud.Science__c + stud.Social__c ;

        Decimal avg = (stud.Telugu__c + stud.Hindi__c + stud.English__c  + stud.Maths__c + stud.Science__c + stud.Social__c)/5;

         stud.Average__c = avg;
         
        
        if(avg >= 80){
            stud.Class__c = 'First Class';
        }else if (avg >= 70 && avg < 80){
            stud.Class__c = 'Second Class';
        }else if ( avg < 70){
            stud.Class__c = 'Third Class';
        }
           
        if(stud.Telugu__c>50 && stud.Hindi__c>50 && stud.English__c> 50 && stud.Maths__c>50 && stud.Science__c> 50 && stud.Social__c > 50){
            stud.Result__c= 'Pass'; 
        }
        else{
            stud.Result__c = 'Fail';
        }
        studList.add(stud);

        try {
            insert studList;
            System.debug('@@@@@@ Student record created @@@@ '+studList);
        }catch(Exception e) {
            return  null;
        }
        return studList;
    }
}