force-app/main/default/objects/Employee__c/fields/Employee_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Employee_FirstName__c</fullName>
    <label>Employee FirstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_LastName__c.field-meta.xml
<CustomField>
    <fullName>Employee_LastName__c</fullName>
    <label>Employee LastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cls_1509_EmplUpdt.cls
public class Cls_1509_EmplUpdt {
    public static void getEmployee(Set<Id> usrId){
        
        List<User> newUser = [SELECT Id, FirstName, LastName, Phone, Email From User where Id In :usrId];
        
        List<Employee__c> newEmpl = new List<Employee__c>();
        for(User Eu : newUser){
            
        Employee__c emp = new Employee__c();
        emp.Employee_FirstName__c = Eu.FirstName;
        emp.Employee_LastName__c = Eu.LastName;
        emp.Contact__c = Eu.Phone;
        emp.Employee_Email__c = Eu.Email;
        emp.Name = Eu.FirstName + ' ' + Eu.LastName;
            newEmpl.add(emp);
        }
        if(newEmpl.size() > 0){
            insert newEmpl;
        }
    }
}