force-app/main/default/objects/CatFactClient__c/CatFactClient__c.object-meta.xml
<CustomObject>
    <label>CatFact</label>
    <nameField>
        <label>CatFactClient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CatFacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CatFactClient__c/fields/Fact__c.field-meta.xml
<CustomField>
    <fullName>Fact__c</fullName>
    <label>Fact</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CatFactClient_21_10.cls
public class CatFactClient_21_10 {

    public void getFacts(){
       Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint('https://catfact.ninja/fact');
        
        HttpResponse res = h.send(req);
        System.debug('res :' + res);
        Integer statusCode = res.getStatusCode();
        System.debug('statusCode :' + statusCode);
		String body = res.getBody();
        System.debug('body :' + body);
        
        //process the response
        catFact cft = (catFact)Json.deserialize(body,catFact.class);
        system.debug('rsponse cft:' + cft);
        //store the object fact
      storeCatFact(cft.fact,cft.length);
    }
    
    //to get the data from db we need to insert the data by creating the method
    public void storeCatFact(String fact, Integer length){ 
        CatFactClient__c cf = new CatFactClient__c(); // intialize the object, save the data into object
        cf.Fact__c = fact;
        cf.Length__c = length; 
        insert cf;
    }
    
    //to convert sring into an object we have to create a class simliar to the data structure at response
    public class catFact{
        public String fact;
        public Integer length;
    }
}