force-app/main/default/objects/House__c/House__c.object-meta.xml
<CustomObject>
    <label>House</label>
    <nameField>
        <label>House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House__c/fields/House_Type__c.field-meta.xml
<CustomField>
    <fullName>House_Type__c</fullName>
    <defaultValue>&quot;none&quot;</defaultValue>
    <label>House Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/House__c/recordTypes/Flat.recordType-meta.xml
<RecordType>
    <fullName>Flat</fullName>
    <active>false</active>
    <label>Flat</label>
</RecordType>

force-app/main/default/objects/House__c/recordTypes/Flats.recordType-meta.xml
<RecordType>
    <fullName>Flats</fullName>
    <active>true</active>
    <label>Flats</label>
</RecordType>

force-app/main/default/objects/House__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/House__c/recordTypes/Terrace.recordType-meta.xml
<RecordType>
    <fullName>Terrace</fullName>
    <active>true</active>
    <label>Terrace</label>
</RecordType>

force-app/main/default/classes/HouseLayout.cls
public class HouseLayout {
    public static void HouseMethod(List<House__c>triggernew){
         Id Flats = Schema.SObjectType.House__c.getRecordTypeInfosByName().get('Flats').getRecordTypeId();//schema represents structure of db
    	 Id Terrace= Schema.SObjectType.House__c.getRecordTypeInfosByName().get('Terrace').getRecordTypeId();//fetch the record type
         Id Individual = Schema.SObjectType.House__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        for(House__c hs : triggernew){//returns new records
            if(hs.RecordTypeId == Flats ){//recordtype
                hs.House_Type__c = 'Flat';//picklist type
            }
        	 if(hs.RecordTypeId == Terrace ){
                hs.House_Type__c = 'Terrace';
            }
             if(hs.RecordTypeId == Individual ){
                hs.House_Type__c = 'Individual';
            }
        }
        
    }
}