force-app/main/default/objects/Books__c/Books__c.object-meta.xml
<CustomObject>
    <label>Books</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Books__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SoqlMethods.cls
public class SoqlMethods {
    public void SoqlMethod(){
        
      /*  List<Account> accList = new List<Account>();
       // Integer c;
        
        //String stuName='Shaik'; //can use variable and query through here
        
        	// c =[SELECT count() From Account Where Name Like 'Shaik irfan%'];
          // accList =[SELECT Id, Name FROM Account WHERE Name = 'Shaik irfan' ORDER By Name];// order in ascending order
        
        
           accList =[SELECT Id, Name,(SELECT Id,Name FROM Contacts) FROM Account WHERE Name = 'Shaik irfan' ];// parent to child 
        
      /*  if(!accList.isEmpty()){ //we can check null point 
            for(Account acc :accList ){ // we can iterate here
                for  (Contact con :acc.Contacts)//p-child 
            }
        }*/
        //system.debug('order :'+ accList);
        
        //Child  to parent with cstom obj
        List<Books__c> bookList = new List<Books__c>();
        bookList = [SELECT Id,Name,Student__c FROM Books__c WHERE Name='Probability' ];
        
        system.debug('bklst'+bookList);
        
        
    }
}