force-app/main/default/objects/Students__c/Students__c.object-meta.xml
<CustomObject>
    <label>Students</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Students__c/fields/Fathers_Name__c.field-meta.xml
<CustomField>
    <fullName>Fathers_Name__c</fullName>
    <label>Fathers Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentOperationsServiceController.cls
public with sharing class StudentOperationsServiceController {
        @AuraEnabled
        public static Boolean saveStudent(String name, String fathersName) {
            Students__c stud = new Students__c() ;
            try {
                stud.Name = name;
                stud.Fathers_Name__c = fathersName;
                update stud;
                System.debug('@@@@@@ Student record created @@@@ '+stud);
            }catch(Exception e) {
                return false;
            }
            return true;
        }

    }